MAX_RAW_SPEC_BYTES = 256_000

MAX_LESSON_BLOCKS = 100
MAX_LOCATIONS = 20
MAX_ROOMS_PER_LOCATION = 20
MAX_INSTRUCTORS = 100
MAX_GROUPS = 200

MAX_LESSONS_PER_GROUP = 14
MAX_DURATION_MINUTES = 24 * 60
MAX_PREFERRED_CLASSES_PER_WEEK = 100

# Candidate assignments are the main driver of solver memory and model size.
MAX_SOLVER_CANDIDATES = 20_000

MAX_ACTIVE_SOLVE_JOBS = 4
MAX_STORED_SOLVE_JOBS = 100
TOTAL_SOLVE_JOB_LIMIT_SECONDS = 130
